# Tensor Introduction

https://github.com/deep-learning-with-pytorch/dlwpt-code/blob/master/p1ch3/1_tensors.ipynb

In [1]:
a = [1.0, 2.0, 1.0]

In [2]:
import torch # <1>
a = torch.ones(3) # <2>
a

tensor([1., 1., 1.])

In [3]:
points = torch.zeros(6) # <1>
points[0] = 4.0 # <2>
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

In [4]:
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points

tensor([4., 1., 5., 3., 2., 1.])

In [5]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [6]:
points.shape

torch.Size([3, 2])

In [7]:
points = torch.zeros(3, 2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [8]:
points[0, 1]

tensor(0.)

In [9]:
points[1, 1]

tensor(0.)

In [10]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

# Named Tensor

In [11]:
img_t = torch.randn(3, 5, 5) # shape [channels, rows, columns]
weights = torch.tensor([0.2126, 0.7152, 0.0722])

In [14]:
img_t

tensor([[[ 0.2091, -0.4634, -4.0032, -0.2158, -0.8116],
         [-1.2628,  1.1057,  1.3183, -0.9460, -0.0710],
         [-0.8744,  0.7402,  0.4206,  0.1479,  1.5134],
         [ 0.5543,  1.3379, -0.4794,  0.8422,  0.1110],
         [-0.5088, -1.1244,  1.1428,  0.1934, -0.6280]],

        [[ 0.5814,  0.1230, -0.2401, -1.3123, -0.4516],
         [-0.7238, -0.4005,  1.6725,  0.1984,  0.0900],
         [-0.2762,  1.2459,  1.1366, -0.8478, -0.3007],
         [-1.5494,  0.8419, -0.6327, -0.6649,  1.1059],
         [ 1.2431,  1.0401,  0.8625,  2.0261, -1.4864]],

        [[ 0.1594, -0.1486, -1.4759, -2.1488, -0.7030],
         [ 0.3402,  0.0172, -0.2079, -0.6072,  0.7271],
         [ 0.5710,  0.4882,  0.8633,  0.4652, -0.0490],
         [ 0.0876, -0.7196,  0.6952,  0.1020,  0.1255],
         [-1.2417, -1.0542, -0.0604,  1.5967, -0.2223]]])

In [15]:
batch_t = torch.randn(2, 3, 5, 5)
batch_t

tensor([[[[ 0.2251,  0.5912,  1.0839, -1.3302,  2.4715],
          [-0.0637, -0.3310,  1.3248,  1.8601, -0.8509],
          [-0.8322, -1.3945,  0.9548, -1.4095,  0.7941],
          [ 2.0767,  0.6913,  0.1778,  1.4430, -0.1810],
          [ 0.3799,  0.6428, -0.9510, -0.2213, -0.2073]],

         [[-0.2179, -0.4666,  0.8641,  0.0151,  0.4984],
          [ 0.5257, -1.7669, -0.0228, -0.8556,  0.2386],
          [-0.3826,  1.0306, -0.9216, -0.0596,  0.0536],
          [ 0.0343,  0.3503, -0.4122, -0.9815,  0.0843],
          [ 1.6070,  0.7835, -0.2080, -1.1080, -0.0315]],

         [[-1.1210,  0.2930,  0.2592,  0.3597, -0.8339],
          [ 0.5963,  0.7622, -0.6031, -0.2334, -0.2561],
          [ 0.4124, -0.4886, -0.5745, -1.5889,  1.0544],
          [-1.3110, -0.5619, -0.6066,  1.6605, -0.3584],
          [ 0.8617, -0.3173,  0.6006,  0.5018,  0.5039]]],


        [[[ 0.7048,  2.7907,  0.3522, -0.7582, -0.6000],
          [ 0.8157, -1.4323, -0.3740, -0.7603, -0.2251],
          [-1.2126,  1.

In [16]:
img_t.mean(-3)

tensor([[ 0.3166, -0.1630, -1.9064, -1.2256, -0.6554],
        [-0.5488,  0.2408,  0.9276, -0.4516,  0.2487],
        [-0.1932,  0.8248,  0.8068, -0.0783,  0.3879],
        [-0.3025,  0.4867, -0.1390,  0.0931,  0.4475],
        [-0.1691, -0.3795,  0.6483,  1.2721, -0.7789]])

In [17]:
batch_t.mean(-3)

tensor([[[-0.3713,  0.1392,  0.7357, -0.3185,  0.7120],
         [ 0.3528, -0.4452,  0.2330,  0.2570, -0.2895],
         [-0.2674, -0.2842, -0.1804, -1.0193,  0.6340],
         [ 0.2667,  0.1599, -0.2804,  0.7073, -0.1517],
         [ 0.9496,  0.3697, -0.1861, -0.2759,  0.0883]],

        [[-0.5795,  0.9582, -0.0866, -0.5304, -0.4801],
         [ 0.7829, -1.4362,  0.0994, -0.1532, -0.2758],
         [-1.0931,  0.5838, -0.5318,  0.3541,  0.2707],
         [-1.0078,  0.3767,  0.5365,  0.2177, -0.1479],
         [ 0.4654,  0.5058,  0.3861,  0.1634, -0.8101]]])

In [20]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)
unsqueezed_weights

tensor([[[0.2126]],

        [[0.7152]],

        [[0.0722]]])

In [21]:
img_weights = (img_t * unsqueezed_weights)
batch_weights = (batch_t * unsqueezed_weights)
img_gray_weighted = img_weights.sum(-3)
batch_gray_weighted = batch_weights.sum(-3)
batch_weights.shape, batch_t.shape, unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [22]:
img_named =  img_t.refine_names(..., 'channels', 'rows', 'columns')
batch_named = batch_t.refine_names(..., 'channels', 'rows', 'columns')
print("img named:", img_named.shape, img_named.names)
print("batch named:", batch_named.shape, batch_named.names)

img named: torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch named: torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/torch/_tensor.py:780: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  ../c10/core/TensorImpl.h:1156.)
  return super(Tensor, self).refine_names(names)
